spring:
  application:
    name: test-redis-service
  redis:
    port: 6379
    host: 192.168.211.136
server:
  port: 7075
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
